version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "pdata@1234"
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared-network

  # --- MongoDB ---
  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: "mdata@1234"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - shared-network

  # (Optional) Web UI for MongoDB
  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: "admin"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_URL: "mongodb://mongo:mdata%401234@mongo:27017/?authSource=admin"
    ports:
      - "8071:8081"
    networks:
      - shared-network

volumes:
  pgdata:
  mongodata:

networks:
  shared-network:
    external: true
